spring.application.name=product-management

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:productdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=false

# JPA / Hibernate Configuration (Otimizado para Testes)
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.main.banner-mode=off

# Redução de verbosidade de logs para acelerar o console
logging.level.root=WARN
logging.level.org.springframework=WARN
logging.level.org.hibernate=WARN